#!/usr/bin/env -S deno run -A
import { workflow } from "jsr:@david/gagen@^0.5.0";

const buildJob = {
  id: "build",
  name: "check updates",
  if: "github.repository == 'dprint/dprint-plugin-mago'",
  runsOn: "ubuntu-latest",
  timeoutMinutes: 45,
  steps: [
    {
      name: "Clone repository",
      uses: "actions/checkout@v6",
      with: { token: "${{ secrets.GH_DPRINTBOT_PAT }}" },
    },
    { uses: "denoland/setup-deno@v2" },
    { uses: "dsherret/rust-toolchain-file@v1" },
    // the update script builds the wasm release as one of its checks.
    {
      name: "Install wasm32 target",
      run: "rustup target add wasm32-unknown-unknown",
    },
    // node is needed so the update script can install and run the OpenAI
    // Codex CLI (@openai/codex) when it has to reconcile a Mago update.
    { uses: "actions/setup-node@v6", with: { "node-version": "24.x" } },
    {
      name: "Run script",
      env: {
        OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}",
        // model that fixes/wires up the Mago update (Codex)
        CODEX_MODEL: "gpt-5.6-terra",
        // separate model that independently reviews the changes
        REVIEW_MODEL: "gpt-5.6-sol",
      },
      run: [
        `git config user.email "dprintbot@users.noreply.github.com"`,
        `git config user.name "dprintbot"`,
        "deno run -A ./scripts/update.ts",
      ],
    },
  ],
} as const;

// This is necessary to prevent GH automatically disabling this workflow after 60 days.
const keepaliveJob = {
  id: "workflow-keepalive",
  if: "github.event_name == 'schedule'",
  runsOn: "ubuntu-latest",
  permissions: { actions: "write" },
  steps: [
    { uses: "liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c" },
  ],
} as const;

workflow({
  name: "check_updates",
  on: {
    workflow_dispatch: {},
    schedule: [
      // do this once per day
      { cron: "0 7 * * *" },
    ],
  },
  jobs: [buildJob, keepaliveJob],
}).writeOrLint({
  filePath: new URL("./check_updates.generated.yml", import.meta.url),
  header: "# GENERATED BY ./check_updates.ts -- DO NOT DIRECTLY EDIT",
  pinDeps: true,
});
